networks:
  toy-exchange-auth-net:

services:
  authentication:
    build:
      context: ../development/backend/authentication
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - APP_HOSTNAME=authentication
      - APP_PORT=3000
      - APP_CONFIG=./dist/config/app-config/prod.config.js
    networks:
      - toy-exchange-auth-net
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://authentication:3000/api/v1/auth/regular-user/health || exit 1"
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 30s
