networks:
  toy-exchange-auth-net-test:

services:
  authentication-test:
    build:
      context: ../development/backend/authentication
      dockerfile: Dockerfile.test
    ports:
      - 3002:3002
    environment:
      - APP_HOSTNAME=authentication-test
      - APP_PORT=3002
      - APP_CONFIG=./dist/config/app-config/test.config.js
    networks:
      - toy-exchange-auth-net-test
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://authentication-test:3002/api/v1/auth/regular-user/health || exit 1"
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 30s
